*&---------------------------------------------------------------------*
*& Report Z_CFOP
*&---------------------------------------------------------------------*
*& Solve Rubik's Cube By CFOP
*&---------------------------------------------------------------------*
************************************************************************
*  程序名：Z_CFOP
*  程序名称：Z_CFOP
*-------------------------------------------------
*  创建日期         程序员        程序类型
*  2021.07.29      JACK LIANG     REPORT
*-------------------------------------------------
*  描述：
*    通过CFOP方法还原魔方
*    项目地址：https://github.com/Jack-Liang/CFOP_ABAP
*=================================================
*  修改日期    请求  版本    修改人      修改描述
*                   1.1
************************************************************************
REPORT Z_CFOP.

INCLUDE Z_CFOP_TOP.
INCLUDE Z_CFOP_CHECK.
INCLUDE Z_CFOP_SEARCH.
INCLUDE Z_CFOP_OPERATE.

SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE TBLOCK1.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 5(23) T_YELLOW.
PARAMETERS: P_YELLOW TYPE C LENGTH 9.
SELECTION-SCREEN END OF LINE.


SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 5(23) T_ORANGE.
PARAMETERS: P_ORANGE TYPE C LENGTH 9.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 5(23) T_BLUE.
PARAMETERS: P_BLUE TYPE C LENGTH 9.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 5(23) T_RED.
PARAMETERS: P_RED TYPE C LENGTH 9.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 5(23) T_GREEN.
PARAMETERS: P_GREEN TYPE C LENGTH 9.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 5(23) T_WHITE.
PARAMETERS: P_WHITE TYPE C LENGTH 9.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN: END OF BLOCK B1.

SELECTION-SCREEN: BEGIN OF BLOCK B2 WITH FRAME TITLE TBLOCK2.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 5(23) T_DETAIL.
PARAMETERS: DETAILS TYPE CHAR1 AS CHECKBOX.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN: END OF BLOCK B2.


SELECTION-SCREEN: BEGIN OF LINE,
  PUSHBUTTON 5(23) SCRAMBLE USER-COMMAND SCRAMBLE.
SELECTION-SCREEN: END OF LINE.


INITIALIZATION.

  TBLOCK1 = '魔方输入'.
  T_YELLOW = '黄色面'.
  T_ORANGE = '橙色面'.
  T_BLUE = '蓝色面'.
  T_RED = '红色面'.
  T_GREEN = '绿色面'.
  T_WHITE = '白色面'.

  TBLOCK2 = '详情'.
  T_DETAIL = '输出技术细节'.
  SCRAMBLE = '生成打乱公式'.

AT SELECTION-SCREEN .
  IF SY-UCOMM = 'SCRAMBLE'.
    P_WHITE = 'WWWWWW'.

    PERFORM FRM_SCRAMBLE.

  ENDIF.




START-OF-SELECTION.

  BREAK-POINT.
